var GAME_LEVELS = [
  ["                                                                   x       x           ",
   "                                                                   x       x           ",
   "                                                                   x       x           ",
   "                                                                   x       x           ",
   "                                                                   x       x           ",
   "                                                    o       o      x       x           ",
   "                                        m      o                  xxx     xxx          ",
   "                     s                             xxxx    xx    xx!xx   xx!xx         ",
   "                                    o o      xx                  x!!!x   x!!!x         ",
   "                                                                 xx!xx   xx!xx         ",
   "               m          o o       xxxxx                xx       xvx    xx!xx         ",
   "                                                   oooo                   xvx      xx  ",
   "  xx           o o      xxxxx              s                       o                x  ",
   "  x                                          xxxx                          o    o   x  ",
   "  x    s      xxxxx               xxxxxx                          xx           ooo  x  ",
   "  x                                                        s              xx        x  ",
   "  x  @                               m            m                xxxxx            x  ",
   "  xxxxxxxxxxxxxxxxxx   xxxxxxxx   xxxxxxxxxx     xxxx    xxxxxxxxx   xxxxxxxxxxxxxxxx  ",
   "                   x   x      x   x        x             x                             ",
   "                   x!!!x      x!!!x        x!!!!!!!!!!!!!x                             ",
   "                   x!!!x      x!!!x        x!!!!!!!!!!!!!x                             ",
   "                   xxxxx      xxxxx        xxxxxxxxxxxxxxx                             ",
   "                                                                                       ",
   "                                                                                       "],
  ["                         s                                    s               ",
   "          o oo           xx          oooo       o oo       xx         oooo    ",
   "          o oo        x       x     oooo    o oo        x       x     oooo    ",
   "                 xx   x       x                      xx   x       x           ",
   "                      x       x                          x       x            ",
   "  xxxxxx   xxxxxxxxxxxxxxxxxxxxxxxxxxxxx   xxxxxx   x   xxxx   xxxxxxx        ",
   "  x    o       o      x       x        x   o       o      x       x       xx  ",
   "  x       xxx        xxx     xxx       x      xxx        xxx     xxx       x  ",
   "  x   xxxx    xx    xx!xx   xx!xx      x  xxxx    xx    xx!xx   xx!xx      x  ",
   "  x    o o    m     x!!!x   x!!!x      x   o o          x!!!x   x!!!x      x  ",
   "  x                 xx!xx   xx!xx      x                xx!xx   xx!xx      x  ",
   "  x  m    xxx  xx    xvx    xx!xx      x  m   xxx  xx    xvx    xx!xx      x  ",
   "  x                          xvx       x                         xvx       x  ",
   "  x            o o o                   x            o o o      m           x  ",
   "  x                   xxxx   o     m   x                   xxxx   o    m   x  ",
   "  x    s      xxxxx          oo        x    s      xxxxx          oo       x  ",
   "  x                                    x                                   x  ",
   "  x  @               m      xxx        x          o        m      xxx      x  ",
   "  xxxxxxxxxxxxxxxxxx   xxxxxxx   xxxxxxxxxxxxxxxxxxxxxxxx   xxxxxxx   xxxxxx  ",
   "                   x   x     x   x                      x   x     x   x       ",
   "                   x!!!x     x!!!x                      x!!!x     x!!!x       ",
   "                   x!!!x     x!!!x                      x!!!x     x!!!x       ",
   "                   xxxxx     xxxxx                      xxxxx     xxxxx       ",
   "                                                                              ",
   "                                                                              "],
  ["                                                                                                              ",
   "          o oo           xx          oooo       o oo       xx         oooo                                    ",
   "                                     x   xxxxxxxxx   xxxxxxxx              x x                                ",
   "                                      x   x           x              x                 x!!!x                  ",
   "             xxx            xxx xxx xxx xxx     o o  x!!!!!!!!!!!!!!x                   vx                    ",
   "                         s    x xxx x x xxx x          x!!!!!!!!!!!!!!x                                       ",
   "                             x             x   xxxxxxxxxxxxxxxxxxxxxxx                                        ",
   "              ooooooo        xx           xx                                         xxx                      ",
   "  xxx                         x     x     x                m                         x!!!x               xxx  ",
   "  x x      m       xxx        x    xxx    x                                          xxx                 x x  ",
   "  x                 x         x    xxx    xxxxxxx              s          xxxxx                            x  ",
   "  x                 x         x           x                              x   x                             x  ",
   "  x       xxx       x         xx          x                              x x x                       m     x  ",
   "  x                 x                     x       |xxxx|    |xxxx|     xxx xxx              s              x  ",
   "  x                xxx             o o    x                              x         xxx                     x  ",
   "  x        xxxx   xxxxx       xx          x                             xxx       x!!!x          x         x  ",
   "  x               oxxxo       x    xxx    x                             x x        xxx          xxx        x  ",
   "  x                xxx        xxxxxxxxxxxxx  x oo x    x oo x    x oo  xx xx                    xxx        x  ",
   "  x      @          x         x           x!!x    x!!!!x    x!!!!x    xx   xx                    x         x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx           xxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                                              ",
   "                                                                                                              "],
  ["                                                                                                  xxx x       ",
   "                                                                                                      x       ",
   "                                                                                                  xxxxx       ",
   "                                                                                                  x           ",
   "                                                                                                  x xxx       ",
   "                          o                                                                       x x x       ",
   "                                                                                             o o oxxx x       ",
   "                   xxx                                                                                x       ",
   "       !  o  !                                                xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx       ",
   "       x     x                             s                   x   x x   x x   x x   x x   x x   x x          ",
   "       x= o  x            x                                   xxx x xxx x xxx x xxx x xxx x xxx x xxxxx       ",
   "       x     x                      m                            x x   x x   x x   x x   x x   x x     x      ",
   "       !  o  !            o                                  xxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxxxx       ",
   "                                                                                                              ",
   "          o              xxx                              xx                                                  ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                      xx              m             s                         ",
   "           o     o     o  ooo   ooooooo                                                                       ",
   "            o   o o   o    o    o     o                                                                       ",
   "             o o   o o     o    o     o                                                                       ",
   "      @       o     o     ooo   o     o                                                                       ",
   "  xxxxxxxxxxx                                                      s                                          ",
   "  x         x o xxxxxxxxx o xxxxxxxxx o xx                                                x                   ",
   "  x         x   x       x   x       x   x                 ||                  x     x                         ",
   "  x  @      xxxxx   o   xxxxx   o   xxxxx                                                                     ",
   "  xxxxxxx                                     xxxxx       xx     xx     xxx                                   ",
   "        x=                  =                =x   x                     xxx                                   ",
   "        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   x!!!!!!!!!!!!!!!!!!!!!xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
